name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch: # 添加这一行，允许手动触发

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: rustup toolchain install stable --profile minimal
            - uses: Swatinem/rust-cache@v2
            - run: cargo build --release
            - run: cargo test
